# Volumetric Flow Labels
Barrels_day = "Barrels/day"
Barrels_hour = "Barrels/hr"
Cfm = "cfm"
Scfm = "scfm"
E3m3_day = "e3m3/day"
E3m3_d = "e3m3/d"
Gpm = "gpm"
L_hour = "l/hr"
M3_hour = "m3/hr"
M3_h = "m3/h"
M3_min = "m3/min"
M3_m = "m3/m"
M3_sec = "m3/sec"
Mmscfd = "mmscfd"
Mmcfd = "mmcfd"
Scfd = "scfd"

# Volumetric Flow Labels For Actuals
Acfm = "acfm"
AE3m3_day = "ae3m3/day"
AE3m3_d = "ae3m3/d"
AM3_hour = "am3/hr"
AM3_h = "am3/h"
AM3_min = "am3/min"
AM3_m = "am3/m"
Mmacfd = "mmacfd"
NM3_h = "Nm3/h"
NM3_hr = "Nm3/hr"

# Legacy Volumetric Flow Labels
Barrels_dayLegacy = "Barrels/d"
E3m3_dayLegacy = "e3m3/d"
M3_hourLegacy = "m3/h"
M3_secLegacy = "m3/s"

# Mass Flow Labels
Kg_h = "kg/h"
Kg_hour = "kg/hr"
Kg_sec = "kg/sec"
Lb_hour = "lb/hr"
Lb_min = "lb/min"
Tonne_day = "tonne/day"
Tonne_d = "tonne/d"
Tonne_hour = "tonne/hr"
Tonne_h = "tonne/h"

# Legacy Mass Flow Labels
Kg_hourLegacy = "kg/h"
Kg_secLegacy = "kg/s"
Lb_hourLegacy = "lb/h"
Lb_minLegacy = "lb/m"
Tonne_dayLegacy1 = "tonne/d"
Tonne_dayLegacy2 = "t/d"
Tonne_hourLegacy1 = "tonne/h"
Tonne_hourLegacy2 = "t/h"